<?php
assume_index();
$consts_list=<<<LIST
MSG_LOGIN_TOO_SHORT
MSG_LOGIN_TOO_LONG
MSG_LOGIN_REGEX
MSG_PASS_TOO_SHORT
MSG_PASS_TOO_LONG
MSG_PASS_DONT_MATCH
MSG_EMAIL_REGEX
MSG_EMAIL_TAKEN
MSG_LOGIN_TAKEN
MSG_INVALID_CAPTCHA
MSG_CONFIRMATION_EMAIL
MSG_CONFIRMATION_EMAIL_TITLE
MSG_CONFIRMATION_EMAIL_SENT
MSG_REGISTRATION_FAILED_LIST
MSG_BOUNTY_ADDED
LIST;

$curr=0;
foreach (split("[\n|\r]", $consts_list) as $value)
{
  define($value,pow(2,$curr));
  $curr++;
}